version: 2.1
orbs:
  orb-tools: circleci/orb-tools@9.0.0
  releaser: puwnz/releaser@<<pipeline.parameters.dev-orb-version>>
parameters:
  dev-orb-version:
    type: string
    default: "0.0.3"
workflows:
  lint_pack-validate_publish-dev:
    context: dev
    jobs:
      - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: puwnz/releaser
          requires:
            - orb-tools/lint
