version: 2.1
orbs:
  orb-tools: circleci/orb-tools@9.0.0
  releaser: puwnz/releaser@<<pipeline.parameters.dev-orb-version>>
parameters:
  # These pipeline parameters are required by the "trigger-integration-tests-workflow"
  # job, by default.
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "0.0.3"
workflows:
  lint_pack-validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint